language: generic
sudo: required
serivces:
  - docker

before_install:
  - docker build -t namng191/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true namng191/docker-react npm run test