language: generic
sudo: required
serivces:
  - docker

before_install:
  - docker build -t namng191/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true namng191/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-263939793006"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY